routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'setting'], function () {
    Route::get('/', 'HomeController@index');
    Route::resource('grv', 'GetGRVController');
    Route::resource('issue', 'IssueController');
    Route::resource('serialized', 'SerializedItemsController');
    Route::resource('serials', 'SerialsearchController');
    Route::resource('warranties', 'ItemWarrantController');
    Route::resource('warrantysetup', 'WarrantyController');
    Route::resource('issueddnote', 'IssuedDnoteController');
    Route::get('issuednote', 'IssueDnoteController@issue');
    Route::post('receive', 'GetGRVController@receive');

    Route::get('/home', 'HomeController@index');
});
Route::resource('setting', 'SettingController');

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $fillable = ['default_value','title','description'];
    protected $dateFormat = 'Y-m-d H:i:s';

}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use App\Setting;
use App\Warrant;
use Serial\Warranty;
use Illuminate\Http\Request;

use App\Http\Requests;
use Serial\GetSageDate;
use Serial\IssueSo;
use Serial\AllGrv;

class SettingController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('setting.index')
            ->withSettings(Setting::all());
    ;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $setting = new \Serial\SerialTrackerSetting();
//        Warranty::warranty()->storeWarranty($request);
        if($request->get('Primary_Serial_Column') > $request->get('Number_of_Serials'))
            {
                flash()->error('Setting','Primary serial column number cannot exceed Number of serials');
                return view('setting.index')
                    ->withSettings(Setting::all());

            }
        //Todo change this whole code crap lot f query

        $setting->updateSetting($request);
//                flash()->success('Setting','Setting saved successfully');

        return view('setting.index')
            ->withSettings(Setting::all())
            ->withMessage(['type'=>'success','msg'=>'Setting saved successfully']);
//            ->withWarrants(Warrant::all())
//            ->with('codes',Warranty::warranty()->getAllcodes())
            ;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }
}

resources/views/setting/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9" style="float: none; margin: 0 auto">
                <div class="panel panel-info">
                    <div class="panel-heading mainThemeColor">
                        <a href="{{route('warrantysetup.create')}}" class="btn btn-sm btn-default btn-raised pull-right">
                            Set warranty
                        </a>
                        {{--<a href="{{url()->previous()}}" class="pull-left">--}}
                            {{--<button class="btn btn-sm btn-default btn-raised">Back</button>--}}
                        {{--</a>--}}
                        <h3 align="center">Setting</h3>
                    </div>
                    <div class="panel-body">
                        <form action="{{route('setting.store')}}" method="post">
                            {{ csrf_field() }}
                        <table width="100%" class="table table-striped table-hover table-responsive display dataTable ">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Description</th>
                                <th class="text-center">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($settings as $setting)
                                <tr>
                                    <td>{{$setting->title}}</td>
                                    <td>{{$setting->description}}</td>
                                    <td >
                                        @if($setting->setting_id == 3)
                                                <select style="width: 100%" class="form-control warrant inputs" id="warrant" name="{{$setting->title}}" required>
                                                        <option value="1" >Consolidated</option>
                                                        <option value="2" >Detailed</option>
                                                </select>
                                            @elseif($setting->setting_id == 6)
                                            <select style="width: 100%" class="form-control validate inputs" id="validate" name="validate" required>
                                                <option value="1" >Validation per serial</option>
                                                <option value="2" >Bulk validation</option>
                                            </select>
                                        @elseif($setting->default_value == 771)
                                            <input name="{{$setting->title}}" required type="text" class="form-control" value="D/N">
                                        @else
                                            <input name="{{$setting->title}}" required type="{{$setting->title == 'Delivery note Type'
                                            || $setting->title == 'Delivery note Number Prefix' ? 'text' : 'number'}}" class="form-control"
                                             max="{{$setting->title == 'Number of Serials' || $setting->title == 'Serials' ? 4 : 10}}"
                                              min="{{$setting->title == 'Number of Serials' || $setting->title == 'Primary Serial Column' ? 1: 1}}"
                                                   value="{{$setting->default_value}}">
                                        @endif
                                    </td>

                                </tr>
                            @endforeach
                            <tfoot>
                            <tr>
                                <th>Title</th>
                                <th>Description</th>
                                <th class="text-center">Action</th>
                            </tr>
                            </tfoot>
                        </table>
                            <hr />
                               <button type="submit" class="btn btn-sm pull-right btn-raised btn-primary">Accept default</button>
                               <button type="submit" class="btn btn-sm pull-right btn-raised btn-success">Change</button>
                                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        $(".warrant").select2();
    </script>
@endsection