routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'setting'], function () {
    Route::get('/', 'HomeController@index');
    Route::resource('grv', 'GetGRVController');
    Route::resource('issue', 'IssueController');
    Route::resource('serialized', 'SerializedItemsController');
    Route::resource('serials', 'SerialsearchController');
    Route::resource('warranties', 'ItemWarrantController');
    Route::resource('warrantysetup', 'WarrantyController');
    Route::resource('issueddnote', 'IssuedDnoteController');
    Route::get('issuednote', 'IssueDnoteController@issue');
    Route::post('receive', 'GetGRVController@receive');

    Route::get('/home', 'HomeController@index');
});
Route::resource('setting', 'SettingController');

app/Http/Controllers/WarrantyController.php
<?php

namespace App\Http\Controllers;

use App\Sageitemsserial;
use App\Warrant;
use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests;
use Serial\Warranty;

class WarrantyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('warranty.index')
            ->withWarranties(Warrant::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('warranty.create')
            ->with('codes',Warranty::warranty()->getAllcodes())
            ->withSuccess('home');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Warranty::warranty()->storeWarranty($request);
        return view('warranty.create')
            ->withCodes(Warranty::warranty()->getAllcodes())
            ->withSuccess('success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $details = Warrant::findorfail($id);
//        dd($details);
        return view('warranty.edit')
            ->with('details',$details)
            ->withId($id)
            ->with('codes',Warranty::warranty()->getAllcodes())
            ->withSuccess('home');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Warrant::destroy($id);
        Warranty::warranty()->storeWarranty($request);
        return view('warranty.create')
            ->withCodes(Warranty::warranty()->getAllcodes())
            ->withSuccess('success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Warrant::destroy($id);
        return view('warranty.index')
            ->withWarranties(Warrant::all())
            ->withSuccess('success');
    }
}

resources/views/warranty/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9" style="float: none; margin: 0 auto">
                <div class="panel panel-info">
                    <div class="panel-heading mainThemeColor">

                        <div>
                            <a href="{{route('warrantysetup.index')}}" class="btn btn-sm btn-default btn-raised pull-right">
                                All Warranties
                                </a>
                            <h3 align="center">Set Items Warranty</h3>

                        </div>

                    </div>
                    <div class="panel-body">
                        <form action="{{route('warrantysetup.store')}}" method="post">
                            {{csrf_field()}}
                            <div class="form-group">
                                <label for="codes">Select item codes</label>
                                <select style="width: 100%" class="form-control warrant inputs" id="codes" name="codes[]" multiple required>
                                    @foreach($codes as $code)
                                        <?php
                                            echo '<option value="'.$code.'">'.$code.'</option>';
                                        ?>
                                    @endforeach
                                </select>
                            </div>
                            <div class="row">
                                <div class="globalmargin col-md-12">Set Warranties Duration(years)</div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label for="service" class="col-sm-4">Service Warranty</label>
                                        <div class="col-sm-8">
                                            <input type="number" required max="50" min="0" class="form-control" id="service" name="service">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label for="labour" class="col-sm-4">Labour Warranty</label>
                                        <div class="col-sm-8">
                                            <input type="number" required max="50" min="0" class="form-control" id="labour" name="labour">
                                        </div>
                                    </div>

                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label for="parts" class="col-sm-4">Parts Warranty</label>
                                        <div class="col-sm-8">
                                            <input type="number" required max="50" min="0" class="form-control" id="parts" name="parts">
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn pull-right btn-raised btn-primary">Save</button>
                        </form>
                        {{--<button type="submit" class="pull-right btn btn-raised btn-success">Save</button>--}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        var msg = '{{$success}}';
        if(msg == 'success')
        {
            sflash({
                title: "Success",
                text: "Warranty added successfully",
                type: "success",
                allowOutsideClick: true,
                showConfirmButton: false,
                timer: 2500
            });
        }
        $(".warrant").select2({
            placeholder : "Select item codes"
        });
    </script>
@endsection

resources/views/warranty/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9" style="float: none; margin: 0 auto">
                <div class="panel panel-info">
                    <div class="panel-heading mainThemeColor">

                        <div>
                            <a href="{{route('warrantysetup.index')}}" class="btn btn-sm btn-default btn-raised pull-right">
                                All Warranties
                            </a>
                            <h3 align="center">Set Items Warranty</h3>

                        </div>

                    </div>
                    <div class="panel-body">
                        <form action="{{route('warrantysetup.update',['id'=>$id])}}" method="post">
                            {{csrf_field()}}
                            {{ method_field('PUT') }}
                            <div class="form-group">
                                <label for="codes">Select item codes</label>
                                <select style="width: 100%" class="form-control warrant inputs" id="codes" name="codes[]" multiple required>
                                    @foreach(json_decode($details->item_codes) as $datail)
                                    <option value="{{$datail}}" selected>{{$datail}}</option>
                                    @endforeach
                                    @foreach($codes as $code)
                                        <?php
                                        echo '<option value="'.$code.'">'.$code.'</option>';
                                        ?>
                                    @endforeach
                                </select>
                            </div>
                            <div class="row">
                                <div class="globalmargin col-md-12">Set Warranties Duration(years)</div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label for="service" class="col-sm-4">Service Warranty</label>
                                        <div class="col-sm-8">
                                            <input type="number" value="{{$details->labour}}" required max="50" min="0" class="form-control" id="service" name="service">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label for="labour" class="col-sm-4">Labour Warranty</label>
                                        <div class="col-sm-8">
                                            <input type="number" value="{{$details->service}}" required max="50" min="0" class="form-control" id="labour" name="labour">
                                        </div>
                                    </div>

                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <label for="parts" class="col-sm-4">Parts Warranty</label>
                                        <div class="col-sm-8">
                                            <input type="number" required max="50" value="{{$details->parts}}" min="0" class="form-control" id="parts" name="parts">
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn pull-right btn-raised btn-primary">Save</button>
                        </form>
                        {{--<button type="submit" class="pull-right btn btn-raised btn-success">Save</button>--}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        var msg = '{{$success}}';
        if(msg == 'success')
        {
            sflash({
                title: "Success",
                text: "Warranty added successfully",
                type: "success",
                allowOutsideClick: true,
                showConfirmButton: false,
                timer: 2500
            });
        }
        $(".warrant").select2({
            placeholder : "Select item codes"
        });
    </script>
@endsection

resources/views/warranty/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9" style="float: none; margin: 0 auto">
                <div class="panel panel-info">
                    <div class="panel-heading mainThemeColor">
                        <a href="{{route('warrantysetup.create')}}" class="btn btn-sm pull-right btn-raised btn-default">Create</a>
                        <h3 class="text-center">All Warranties</h3>

                    </div>
                    <div class="panel-body">
                        <div class="row">
                            @if(count($warranties) == 0)
                                <h4 class="text-center">no warranty , click here <a href="{{route('warrantysetup.create')}}">
                                        Create
                                    </a> to add item warranty
                                </h4>
                                @endif
                            @foreach($warranties as $warranty)
                                <div class="col-sm-4">
                                    <div class="panel panel-default">
                                        <div class="panel-heading text-center">
                                            <h4>Warranty Details</h4>
                                                    <h5>Labour : {{$warranty->labour}} year{{$warranty->labour>1 ? 's' : ''}}</h5>
                                                    <h5>Service : {{$warranty->service}} year{{$warranty->service>1 ? 's' : ''}}</h5>
                                                    <h5>Labour : {{$warranty->parts}} year{{$warranty->parts>1 ? 's' : ''}}</h5>

                                        </div>
                                        <div class="panel-body">
                                            <h5>Item codes</h5>
                                            <?php
                                                foreach (json_decode($warranty->item_codes) as $item_code)
                                                    {
                                                        echo '<button class="btn btn-success btn-xs mainThemeColor" style="color: #ffffff">'.$item_code.'</button>';
                                                    }
                                                ?>
                                        </div>
                                        <div class="panel-footer">
                                            <div class="row">
                                                <form action="{{url('warrantysetup/'.$warranty->id)}}" method="post">
                                                    <input type="hidden" name="_method" value="DELETE"/>
                                                    {{csrf_field()}}
                                                <button type="submit" class="fa btn btn-sm btn-danger btn-raised colorwhite pull-right fa-trash fl"></button>
                                                </form>
                                                <a href="{{route('warrantysetup.edit',['id'=>$warranty->id])}}" class="fa btn btn-sm btn-success btn-raised colorwhite pull-right fa-pencil fl"></a>
                                            </div>
                                        </div>
                                </div>
                                </div>
                                @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')

@endsection