routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'setting'], function () {
    Route::get('/', 'HomeController@index');
    Route::resource('grv', 'GetGRVController');
    Route::resource('issue', 'IssueController');
    Route::resource('serialized', 'SerializedItemsController');
    Route::resource('serials', 'SerialsearchController');
    Route::resource('warranties', 'ItemWarrantController');
    Route::resource('warrantysetup', 'WarrantyController');
    Route::resource('issueddnote', 'IssuedDnoteController');
    Route::get('issuednote', 'IssueDnoteController@issue');
    Route::post('receive', 'GetGRVController@receive');

    Route::get('/home', 'HomeController@index');
});
Route::resource('setting', 'SettingController');

resources/views/Serialized/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9" style="float: none; margin: 0 auto">
                <div class="panel panel-info">
                    <div class="panel-heading mainThemeColor">
                        <h3 align="center">Serialized Goods Received Vouchers</h3>
                    </div>
                    <div class="panel-body">
                        <table id="example" width="100%" class="table table-striped able-hover table-responsive display dataTable">
                            <thead>
                            <tr>
                                <th>NO :</th>
                                <th>GRV NUMBER</th>
                                <th>Description</th>
                                <th>Supplier</th>
                                <th>Status</th>
                                <th>Date</th>
                                <th class="text-center">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($grvlines as $grvline)
                                <tr class="<?php if($grvline->status == \App\Grv::UNSERIALIZED_GRV)
                                {
                                    echo 'notSerialized';
                                }

                                elseif($grvline->status == \App\Grv::PARTIALLY_SERIALIZED_GRV)
                                {
                                    echo 'partSerialized';
                                }
                                else{
                                    echo 'fullySerialized';
                                }
                                ?>">
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$grvline->GrvNumber}}</td>
                                    <td>{{ucwords($grvline->Description)}}</td>
                                    <td>{{ucwords($grvline->cAccountName)}}</td>
                                    <td>{{$grvline->status}}</td>
                                    <td>{{\Carbon\Carbon::parse($grvline->DeliveryDate)->format(\Serial\Helper::helper()->dateFormat())}}</td>
                                    <td >
                                        {{--<a href="{{route('grv.edit',['id'=>$grvline->autoindex_id])}}"><p class="pull-right btn btn-raised btn-success">Receive</p></a>--}}
                                        <a class="issuecolor linkstyle" href="{{route('serialized.show',['id'=>$grvline->autoindex_id])}}">
                                            <i class="fa fa-eye fa-lg"></i> View
                                        </a>
                                        @if($grvline->status != \App\Grv::SERIALIZED_GRV)
                                        <a class="viewcolor linkstyle" href="{{route('grv.edit',['autoindex_id'=>$grvline->autoindex_id])}}">
                                            <i class="fa fa-check-square-o"></i> Receive Fully
                                        </a>
                                            @endif
                                    </td>

                                </tr>
                            @endforeach
                            <tfoot>
                            <tr>
                                <th>NO :</th>
                                <th>GRV NUMBER</th>
                                <th>Description</th>
                                <th>Supplier</th>
                                <th>Status</th>
                                <th>Date</th>
                                <th class="text-center">Action</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        } );
    </script>
@endsection

resources/views/Serialized/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9" style="float: none; margin: 0 auto">
                <div class="panel panel-info">
                    <div class="panel-heading mainThemeColor">
                        <a href="{{url()->previous()}}" class="pull-left"><button class="btn btn-sm btn-default btn-raised">Back</button></a>
                        <h3 align="center">Serialized Goods Received Vouchers Items</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-6">
{{--                                <h5>GRV ID: {{$details->first()->GrvID}}</h5>--}}
                                <h5>GRV NO: {{$details->first()->GrvNumber}}</h5>
                                <h5>GRV Description: {{ucwords($details->first()->Description)}}</h5>
                                <h5>GRV Account Name: {{ucwords($details->first()->cAccountName)}}</h5>
                            </div>
                            <div class="col-md-6">
                                @if($details->first()->OrderNum != 0)
                                <h5>GRV Order No: {{$details->first()->OrderNum}}</h5>
                                @endif
                                <h5>GRV Invoice Date: {{$details->first()->InvDate}}</h5>
                                <h5>GRV Order Date: {{\Carbon\Carbon::parse($details->first()->OrderDate)->format(\Serial\Helper::helper()->dateFormat())}}</h5>
                                <h5>GRV Delivery Date: {{\Carbon\Carbon::parse($details->first()->DeliveryDate)->format(\Serial\Helper::helper()->dateFormat())}}</h5>
                            </div>
                        </div>
                        <hr />
                        <div class="col-md-12">
                            <table id="example" width="100%" class="table table-striped table-hover table-responsive display dataTable">
                                <thead>
                                <tr>
                                    <th>No :</th>
                                    <th>Item Code</th>
                                    <th>Description</th>
                                    <th class="text-right">Ordered Qty</th>
                                    <th class="text-right">To be RCVD Qty</th>
                                    <th class="text-right">RCVD Qty</th>
                                    {{--<th>Date RCVD</th>--}}
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($grvItems as $item)
                                    <tr class="{{$item['has_warranty'] == 'no'?'errorTd':''}}">
                                        <td>{{$loop->iteration}}</td>
                                        <td class="globalmargin"> {{$item['code']}}</td>
                                        <td class="globalmargin">{{ucwords($item['description'])}}</td>
                                        <td class="text-right globalmargin">{{$item['fQuantity']}}</td>
                                        <td class="text-right globalmargin">{{$item['qty_remaining']}}</td>
                                        <td class="text-right globalmargin">{{$item['qty_serialized']}}</td>
{{--                                        <td>{{\Carbon\Carbon::parse($item['created_at'])->format(\Serial\Helper::helper()->dateFormat())}}</td>--}}
                                    </tr>
                                @endforeach
                                <tfoot>
                                <tr>
                                    <th>No :</th>
                                    <th>Item Code</th>
                                    <th>Description</th>
                                    <th>Ordered Qty</th>
                                    <th class="text-right">To be RCVD Qty</th>
                                    <th class="text-right">RCVD Qty</th>
                                    {{--<th>Date RCVD</th>--}}
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection